version = "2"
com = "same"

[behavior]
quit_server_on_exit = true
confirm_quit = true

[coverart]
align = "bottom left"
size_scale = 0
hidden = false
protocols = ["iterm2", "sixel", "kitty", "ueberzug"]

[style.library]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"
highlight_symbol = "ðŸ“‚"

[style.playlist]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"
highlight_symbol = "ðŸ’¿"
current_track_symbol = "ðŸ”Š "
use_loop_mode_symbol = true

[style.lyric]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"

[style.progress]
foreground_color = "LightBlack"
background_color = "Reset"
border_color = "Blue"

[style.important_popup]
foreground_color = "Yellow"
background_color = "Reset"
border_color = "Yellow"

[style.fallback]
foreground_color = "Foreground"
background_color = "Reset"
border_color = "Blue"
highlight_color = "LightYellow"

[theme]
file_name = "Sweetlove"
name = "Sweet Love"
author = "Boroshlawa"

[theme.primary]
background = "#1f1f1f"
foreground = "#c0b18b"

[theme.cursor]
text = "#1f1f1f"
cursor = "#c0b18b"

[theme.normal]
black = "#4a3637"
red = "#d17b49"
green = "#7b8748"
yellow = "#af865a"
blue = "#535c5c"
magenta = "#775759"
cyan = "#6d715e"
white = "#c0b18b"

[theme.bright]
black = "#402e2e"
red = "#ac5d2f"
green = "#647035"
yellow = "#8f6840"
blue = "#444b4b"
magenta = "#614445"
cyan = "#585c49"
white = "#978965"

[keys]
escape = "escape"
quit = "q"

[keys.view]
view_library = "1"
view_database = "2"
view_podcasts = "3"
open_config = "shift+C"
open_help = "control+h"

[keys.navigation]
up = "i"
down = "e"
left = "n"
right = "o"
goto_top = "g"
goto_bottom = "shift+G"

[keys.global_player]
toggle_pause = "space"
next_track = "shift+N"
previous_track = "control+n"
volume_up = "="
volume_down = "-"
seek_forward = "f"
seek_backward = "b"
speed_up = "control+f"
speed_down = "control+b"
toggle_prefetch = "control+g"
save_playlist = "control+s"

[keys.global_lyric]
adjust_offset_forwards = "shift+F"
adjust_offset_backwards = "shift+B"
cycle_frames = "shift+T"

[keys.library]
load_track = "l"
load_dir = "shift+L"
delete = "d"
yank = "y"
paste = "p"
cycle_root = "o"
add_root = "a"
remove_root = "shift+A"
search = "/"
youtube_search = "s"
open_tag_editor = "t"

[keys.playlist]
delete = "d"
delete_all = "shift+D"
shuffle = "r"
cycle_loop_mode = "m"
play_selected = "l"
search = "/"
swap_up = "shift+I"
swap_down = "shift+E"
add_random_songs = "s"
add_random_album = "shift+S"

[keys.database]
add_selected = "l"
add_all = "shift+L"

[keys.podcast]
search = "s"
mark_played = "m"
mark_all_played = "shift+M"
refresh_feed = "r"
refresh_all_feeds = "shift+R"
download_episode = "d"
delete_local_episode = "shift+D"
delete_feed = "x"
delete_all_feeds = "shift+X"

[keys.adjust_cover_art]
move_left = "control+shift+arrowleft"
move_right = "control+shift+arrowright"
move_up = "control+shift+arrowup"
move_down = "control+shift+arrowdown"
increase_size = "control+shift+pageup"
decrease_size = "control+shift+pagedown"
toggle_hide = "control+shift+end"

[keys.config]
save = "control+s"

[ytdlp]
extra_args = ""
